# Defines FastAPI and Nginx services.

version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi